org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

libVersion=e11d0c70d4

extType=music
extId=youtube-music
extClass=YoutubeExtension

extIconUrl=https://music.youtube.com/img/favicon_144.png
extName=Youtube Music
extDescription=Youtube Music Extension for Echo, with the help of YTM-kt library.

extAuthor=Echo
extAuthorUrl=https://github.com/brahmkshatriya/Echo

extRepoUrl=https://github.com/ram222-git/echo-youtube-extension
extUpdateUrl=https://api.github.com/repos/ram222-git/echo-youtube-extension/releases
